# Generated by Django 4.0.1 on 2022-02-03 15:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('softdesk', '0007_rename_project_id_contributor_project_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='contributor',
            unique_together=set(),
        ),
    ]
